[theme]
theme = "nord-dark"
[icons]
icons = "awesome6"

[[block]]
block = "custom"
cycle = [
    "brightnessctl set 5% >> /dev/null && echo '{\"icon\": \"backlight\", \"text\": \"5%\"}'", 
    "brightnessctl set 50% >> /dev/null && echo '{\"icon\": \"backlight\", \"text\": \"50%\"}'", 
    "brightnessctl set 100% >> /dev/null && echo '{\"icon\": \"backlight\", \"text\": \"100%\"}'", 
]
interval = "once"
json = true

[[block]]
block = "custom"
cycle = [
    "brightnessctl --device='tpacpi::kbd_backlight' set 0 >> /dev/null && echo '{\"icon\": \"keyboard\", \"text\": \"0%\"}'", 
    "brightnessctl --device='tpacpi::kbd_backlight' set 1 >> /dev/null && echo '{\"icon\": \"keyboard\", \"text\": \"100%\"}'",
]
interval = "once"
json = true

[[block]]
block = "custom"
cycle = [
	"setxkbmap -layout us && echo '{\"icon\": \"keyboard\", \"text\": \"US\"}'", 
	"setxkbmap -layout de && echo '{\"icon\": \"keyboard\", \"text\": \"DE\"}'", 
]
#interval = "once"
json = true

[[block]]
block = "net"
#on_click = "alacritty -e nmtui"
#interface_name_exclude = ['br\-[0-9a-f]{12}', 'docker\d+']
#interface_name_include = []
[[block.click]]
button = "left"
cmd = "alacritty -e nmtui"

[[block]]
block = "bluetooth"
mac = "88:D0:39:A7:27:16"

[[block]]
block = "sound"
#format = " $icon $volume "
headphones_indicator = true
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pavucontrol"


[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
full_format = " $icon $percentage {$time |}"
empty_format = " $icon $percentage {$time |}"

[[block]]
block = "time"
interval = 60
#[block.format]
#full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:fr_BE) "
#short = " $icon $timestamp.datetime(f:%R) "
