[theme]
name = "solarized-dark"
[icons]
name = "awesome"

[[block]]
block = "cpu"

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ['br\-[0-9a-f]{12}', 'docker\d+']
interface_name_include = []

[[block]]
block = "bluetooth"
mac = "88:D0:39:A7:27:16"
hide_disconnected = true

[[block]]
block = "sound"
on_click = "pavucontrol"
format = "{volume}"
headphones_indicator = true

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 10

[[block]]
block = "time"
format = "%a %d/%m %R"
interval = 60
