[theme]
name = "solarized-dark"
[icons]
name = "awesome"

[[block]]
block = "custom"
cycle = [
    "brightnessctl set 5% >> /dev/null && echo '{\"icon\": \"backlight_1\", \"text\": \"5%\"}'", 
    "brightnessctl set 50% >> /dev/null && echo '{\"icon\": \"backlight_7\", \"text\": \"50%\"}'", 
    "brightnessctl set 100% >> /dev/null && echo '{\"icon\": \"backlight_full\", \"text\": \"100%\"}'", 
]
interval = "once"
json = true

[[block]]
block = "custom"
cycle = [
    "brightnessctl --device='tpacpi::kbd_backlight' set 0 >> /dev/null && echo '{\"icon\": \"keyboard\", \"text\": \"0%\"}'", 
    "brightnessctl --device='tpacpi::kbd_backlight' set 1 >> /dev/null && echo '{\"icon\": \"keyboard\", \"text\": \"100%\"}'",
]
interval = "once"
json = true

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ['br\-[0-9a-f]{12}', 'docker\d+']
interface_name_include = []

[[block]]
block = "bluetooth"
mac = "88:D0:39:A7:27:16"
hide_disconnected = true

[[block]]
block = "sound"
on_click = "pavucontrol"
format = "{volume}"
headphones_indicator = true

[[block]]
block = "custom"
cycle = [
    "setxkbmap -layout de && echo '{\"icon\": \"keyboard\", \"text\": \"DE\"}'", 
    "setxkbmap -layout us && echo '{\"icon\": \"keyboard\", \"text\": \"US\"}'", 
]
interval = "once"
json = true

[[block]]
block = "time"
format = "%a %d/%m %R"
interval = 60
